/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package map;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import org.jxmapviewer.viewer.GeoPosition;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Font;
import java.net.URI;
import javax.swing.*;
import javax.swing.plaf.FontUIResource;

/**
 * @author Jordan, Clare, Wesley
 * This file is your home screen.
 * Customizable aspects include: home state, background picture, url for heatmap, information massage.
 */

public class Home_Screen extends javax.swing.JFrame {

    /**
     * Creates new form Home_Screen
     */
     
    public Home_Screen() {
      
        initComponents();
        this.setTitle("Colorado School of Mines Library Visitor Pin Map");
        this.setExtendedState(Main.MAXIMIZED_BOTH);
   
        // what is this code, can it be deleted?
        State_Map.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e) {
                if(e.getClickCount() == 1){
                    System.out.println("State Map");
                }
            }
        });
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        State_Map = new javax.swing.JButton();
        World_Map = new javax.swing.JButton();
        US_Map = new javax.swing.JButton();
        HeatmapButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        State_Map.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        State_Map.setForeground(new java.awt.Color(153, 0, 0));
        State_Map.setText("Colorado");
        State_Map.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                State_MapActionPerformed(evt);
            }
        });
        jPanel1.add(State_Map, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 340, 140));

        World_Map.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        World_Map.setForeground(new java.awt.Color(153, 0, 0));
        World_Map.setText("World");
        World_Map.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                World_MapActionPerformed(evt);
            }
        });
        jPanel1.add(World_Map, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 540, 340, 140));

        US_Map.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        US_Map.setForeground(new java.awt.Color(153, 0, 0));
        US_Map.setText("United States");
        US_Map.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                US_MapActionPerformed(evt);
            }
        });
        jPanel1.add(US_Map, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 540, 340, 140));

        HeatmapButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        HeatmapButton.setText("Click Here to See Where People are From!");
        HeatmapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeatmapButtonActionPerformed(evt);
            }
        });
        jPanel1.add(HeatmapButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 770, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("About the App");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 860, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        jLabel3.setLabelFor(jLabel2);
        jLabel3.setText("Welcome to the Colorado School of Mines Maps Collection!");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 2040, 180));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Find a Map from Your Hometown/Country/State!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 860, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Produced by Colorado School of Mines Field Session");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/map/new_colorado_map.png"))); // NOI18N
        jLabel2.setText("Produced by Colorado School of Mines Field Session");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, 1910, 1290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void State_MapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_State_MapActionPerformed
        // handling a click on the state button
        new Main(1).setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_State_MapActionPerformed

    private void World_MapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_World_MapActionPerformed
        // handling a click on the worl button
        new Main(3).setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_World_MapActionPerformed

    private void US_MapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_US_MapActionPerformed
        // handling a click on the us button
        new Main(2).setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_US_MapActionPerformed

    private void HeatmapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeatmapButtonActionPerformed
        // handling a click on the heatmap button
        try {
            String url = "https://arcg.is/1KO4XS0";      // TODO : change the url
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (java.io.IOException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_HeatmapButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // handling a click on the information button
        // if you change the code please add your information to this pane, please do not remove the original information
        JLabel label = new JLabel("<html>This Application was created by Mines 2022 Fall Field Session by: <br/> Jordan Ehrlich <br/> Clare Garski <br/> Wesley Golliher</html>");
        label.setFont(new Font("Arial", Font.PLAIN, 12));
        JOptionPane.showMessageDialog(null, label, "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Screen().setVisible(true);
            }
        });
           
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HeatmapButton;
    private javax.swing.JButton State_Map;
    private javax.swing.JButton US_Map;
    private javax.swing.JButton World_Map;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
